# Generated by Django 3.1 on 2021-06-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default='9a791f', max_length=6, primary_key=True, serialize=False),
        ),
    ]
