# Generated by Django 3.1 on 2021-07-13 21:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20210628_0042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=uuid.uuid4, max_length=6, primary_key=True, serialize=False),
        ),
    ]
