# Generated by Django 3.1 on 2021-07-13 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
